version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
# 5775    UDP     agent   accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - "5775:5775/udp"
# 6831    UDP     agent   accept jaeger.thrift over compact thrift protocol
      - "6831:6831/udp"
# 6832    UDP     agent   accept jaeger.thrift over binary thrift protocol
      - "6832:6832/udp"
# 5778    HTTP    agent   serve configs
      - "5778:5778"
# 16686   HTTP    query   serve frontend
      - "16686:16686"
# 14268   HTTP    collector       accept jaeger.thrift directly from clients
      - "14268:14268"
# 14250   HTTP    collector       accept model.proto
      - "14250:14250"
# 9411    HTTP    collector       Zipkin compatible endpoint (optional)
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - jaeger-app
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.k.voronenko.net`)"
      - "traefik.http.routers.jaeger.entrypoints=web"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.services.jaeger-secure.loadbalancer.server.port=16686"
      - "traefik.http.routers.jaeger-secure.entrypoints=websecure"
      - "traefik.http.routers.jaeger-secure.rule=Host(`jaeger.k.voronenko.net`)"
#      - "traefik.http.routers.jaeger-secure.middlewares=traefik-auth"
      - "traefik.http.routers.jaeger-secure.tls=true"

networks:
  jaeger-app:
  traefik-public:
    external: true

